### ISSUE TITLE
SIdekiq-PRO reliable fetch compatiblity?

### ISSUE THREAD

**Issue by palanglung** [ixti/sidekiq-throttled#11]
Quick Question is it compatible with sidekiq-pro reliable fetch?

**Comment by ixti** [comment]
Unfortunately not. Due to licensing it's not even possible. The only thing that will be possible is extracting throttle strategies from this gem into a standalone gem (I actually plan to do this) and utilize them separately. This will make it possible to use it anywhere in general :D

**Comment by zenzei** [comment]
Hi @ixti , sorry to write to this old issue. 
Maybe is possible to use sidekiq-pro reliable fetch only when available on the users path/bundle (with something like `...if (defined?(Sidekiq::Pro))...`), and if it's not available using the common fetch? Or that also break licensing?

**Comment by ixti** [comment]
@zenzei the problem not in checking if `Sidekiq::Pro` exists or not. I don't know it's API and in order to hook into it I will need to know it and most likely in attempt to override some of it's pices I will have to reveal it's "secret" sauce, which will lead to licensing issue. I think the best way here is to write up own open-source reliable fetch (sidekiq pro according to it's website is using 2 queues and if I understand correctly `UnitOfWork#ack` (stub) is used exactly to notify that job can be removed from the list of currently processed jobs - so it should not be terribly hard to implement it) and make it compatible with sidekiq-throttled.

**Comment by zenzei** [comment]
Sorry @ixti i don't full know the internals of sidekiq/sidekiq pro, i thought it was just a matter of plug&play like it was done in a similar gem (sidekiq-rate-limiter).

**Comment by ixti** [comment]
@zenzei other gems use middleware to handle throttling. Thus it affects for example statistics.
The only thing we do in middleware is "cleaning up" concurrency limiter, although most likely we will move away from that as well (it's possible to do that in a different way).

**Comment by masterkain** [comment]
wow, took me a while to figure out why the entire gem was not working due to reliable fetch. thanks
