### ISSUE TITLE
`ArgumentError: missing keyword: :with (ArgumentError)` with sidekiq-throttled 1.5.0 when using only `sidekiq_throttle_as`

### ISSUE THREAD

**Issue by mudge** [ixti/sidekiq-throttled#198]
Upgrading to [sidekiq-throttled 1.5.0](https://github.com/ixti/sidekiq-throttled/releases/tag/v1.5.0) immediately caused the following error in our application:

```
ArgumentError: missing keyword: :with (ArgumentError)
  sidekiq-throttled (1.5.0) lib/sidekiq/throttled/strategy.rb:83:in `requeue_throttled'
  sidekiq-throttled (1.5.0) lib/sidekiq/throttled.rb:105:in `block in requeue_throttled'
  sidekiq-throttled (1.5.0) lib/sidekiq/throttled/registry.rb:54:in `get'
  sidekiq-throttled (1.5.0) lib/sidekiq/throttled.rb:104:in `requeue_throttled'
  sidekiq-throttled (1.5.0) lib/sidekiq/throttled/patches/throttled_retriever.rb:15:in `retrieve_work'
```

Our application is configured with a single entry in its registry, shared among multiple job definitions:

```ruby
# config/initializers/sidekiq.rb
Sidekiq::Throttled::Registry.add(:third_party_api, threshold: { limit: 15, period: 1.minute }, concurrency: { limit: 5 })
```

With the worker definitions containing code like so:

```ruby
class ThirdPartyApiWorker
  include Sidekiq::Worker

  sidekiq_throttle_as :third_party_api
end
```

Looking at the stack trace and [changes between 1.4.0 and 1.5.0](https://github.com/ixti/sidekiq-throttled/compare/v1.4.0...v1.5.0), it seems that [`Sidekiq::Throttled.requeue_throttled` expects the job class to define the new `sidekiq_throttled_requeue_options` class attribute](https://github.com/ixti/sidekiq-throttled/compare/v1.4.0...v1.5.0#diff-f9200972b6d9ede7fbacfce5b6d20703a9bec6c3072e9d13f0125f651c5a9b4fR105) but using only `sidekiq_throttle_as` does not define this attribute, only [`sidekiq_throttle` does](https://github.com/ixti/sidekiq-throttled/compare/v1.4.0...v1.5.0#diff-5efcdb87c7cdfb7a880ab62bc6482f321b5bd588d370e0b760d8faf87e098d67R99).

There doesn't seem to be coverage in the specs for how `sidekiq_throttle_as` should affect `sidekiq_throttled_requeue_options`.

**Comment by mnovelo** [comment]
@anero any thoughts on this issue?

**Comment by caseydriscoll** [comment]
We are seeing this too

**Comment by anero** [comment]
I folks, sorry for the inconvenience. I'll look into this today.

**Comment by anero** [comment]
I spent some time looking into this yesterday, we weren't aware of this other way to set up throttling using `sidekiq_throttle_as`. It's not documented on the README and it wasn't mentioned during the PR review, so we completely missed it.

The problem is that we're currently storing the requeue config on `Sidekiq::Throttled::Job.sidekiq_throttled_requeue_options`, which is set when you call `sidekiq_throttle`. But there's no way we can do a similar thing when defining the strategy with `Sidekiq::Throttled::Registry.add` (because there's no job class at that point). We could allow defining the requeuing options as arguments on `sidekiq_throttle_as`, but that doesn't feel right, instead you probably want to define the option when registering the strategy.

So we think that the correct solution here would be to avoid storing the requeue options on `sidekiq_throttled_requeue_options`, and instead store them on the `Strategy` object itself, as it's done for `concurrency`, `threshold`, `key_suffix` and `observer`. That way we could use the same mechanism for both `sidekiq_throttle` and `sidekiq_throttle_as`. This will require a bunch of internal refactoring though, so before proceeding I'd appreciate any feedback others have on this approach or other suggestions to fix the error.

**Comment by ixti** [comment]
@anero yeah, I forgot about that one myself, LOL. The way strategies are registered needs to be refactored (planning on that for too long now).

I'm not against moving requeue options into the strategy for now though.
